select getclassepontos(total_pontos) as total_pontos,
getnomecurso(curso) as curso,
getgraucurso(curso) as grau,
getperiodocurso(curso) as periodo,
sexo,
getfaixaidade(idade) as idade,
local_origem,
tipo_instituicao,
renda_familiar,
tipo_residencia,
grau_escolaridade,
motivo,
transporte,
instrucao_pai,
instrucao_mae,
automovel,
livros,
leitura,
internet 
from socioeconomica;
